### ISSUE TITLE
Failed to install - (more a request of help then a issue )

### ISSUE THREAD

**Issue by digas** [chitoku-k/edgerouter-exporter#446]
Hi can you help me , i'm following your install instructions:

my router version: EdgeRouter X v1.10.11
since i'm using a ER-X  i'm following the MediaTek-based instructions

```
root@router:/tmp# sudo mkdir -p /config/data/firstboot/install-packages
root@router:/tmp# mv prometheus-edgerouter-exporter_mipsel.deb /config/data/firstboot/install-packages

root@router:/tmp# sudo dpkg -i /config/data/firstboot/install-packages/prometheus-edgerouter-exporter_mipsel.deb
dpkg-deb: error: archive '/config/data/firstboot/install-packages/prometheus-edgerouter-exporter_mipsel.deb' contains not understood data member control.tar.xz, giving up
dpkg: error processing /config/data/firstboot/install-packages/prometheus-edgerouter-exporter_mipsel.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /config/data/firstboot/install-packages/prometheus-edgerouter-exporter_mipsel.deb
```

**Comment by chitoku-k** [comment]
Hi, thanks for filing this.

It seems that the version of dpkg in EdgeOS v1.10.11 is too old to handle the currently distributed package format (xz). Can you show which dpkg version does your installation have so I can package it in a different format?

```
$ apt-cache policy dpkg
```

**Comment by chitoku-k** [comment]
As I extracted the OS image of EdgeOS v1.10.11 and checked on `/var/lib/pkg/status`, it turns out that it does not work anyway even I package it in a different format. EdgeOS v1.10.11 is based on Debian “wheezy” and comes with libc6 2.13-38+deb7u11 but edgerouter-exporter only works with libc6 \>= 2.23[^1]. Closing as I don’t think I can easily provide a binary for such an old release with the current infrastructure but feel free to open a PR if it’s possible.

[^1]: https://github.com/chitoku-k/edgerouter-exporter/blob/v2.9.3/Cargo.toml#L11

**Comment by digas** [comment]
Understood , thanks for all the investigation i was not expecting it from you ;) .
I was not updating as i'm using a specific CA cert on this for some reasons , but i will give a try and i should update ;) , to the latest version. Thanks .
